name: test

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "feature/** (Enter **)"


jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch --all
    - run: |
        git checkout -b ${BRANCH_NAME}
        git push origin HEAD
      env:
        BRANCH_NAME: "feature/${{ inputs.branch_name }}"