name: test

on:
  workflow_dispatch:
    inputs:
      personalAccessToken:
        description: 'Your Personal Access Token'
        required: true
      private_key:
        description: "Private key of GITHUB APP"
        required: true
env:
  GITHUB_TOKEN: ${{ inputs.personalAccessToken  }}
  APP_SLUG: "terraform-ghaction-e"

jobs:
  action_test:
    runs-on: ubuntu-latest
    steps:
    - id: app_id
      run: |
        # https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-app
        app_id=$(gh api -H "Accept: application/vnd.github+json" \
          /apps/${APP_SLUG} | jq -r .id)
        echo "APP_ID=${app_id}" >> $GITHUB_ENV
      env:
        APP_SLUG: ${{ env.APP_SLUG }}
    - uses: actions/checkout@v3
    - uses: ./register-github-secret/
      with:
        token: ${{ inputs.personalAccessToken }}
        value: ${{ env.APP_ID }}
        action_repository: ${{ github.repository }}
        key: "APP_ID_TEST"
    # - run: | 
    #     tmp=$(echo ${private_key} | sed 's/\\n/\n/g')
    #     echo 'PRIVATE_KEY=${PRIVATE_KEY}' >> $GITHUB_ENV
    #   env:
    #     private_key: ${{ inputs.private_key }}
    - uses: ./register-github-secret/
      with:
        token: ${{ inputs.personalAccessToken }}
        value: ${{ inputs.private_key }}
        action_repository: ${{ github.repository }}
        key: "PRIVATE_KEY_TEST"
    - uses: ./generate-github-app-token
      with:
        private_key: ${{ secrets.PRIVATE_KEY_TEST }}
        app_id: ${{ secrets.APP_ID_TEST }}


